name: Log ISS Location Data Daily

on:
  workflow_dispatch: # Allows manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2004142@ds.study.iitm.ac.in
        run: echo "Hello, world!"